config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :users do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  private
    def downcase_email
      self.email = email.downcase
    end

    class << self
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
  
      def new_token
        SecureRandom.urlsafe_base64
      end
    end
  
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def index
      @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @dishes = @user.dishes.paginate(page: params[:page], per_page: 5)
    @log = Log.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Make every day happy with cookingへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      @user.destroy
      flash[:success] = "ユーザーの削除に成功しました"
      redirect_to users_url
    elsif current_user?(@user)
      @user.destroy
      flash[:success] = "自分のアカウントを削除しました"
      redirect_to root_url
    else
      flash[:danger] = "他人のアカウントは削除できません"
      redirect_to root_url
    end
  end



  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def user_params_update
      params.require(:user).permit(:name, :email, :introduction, :gender)
    end

    def correct_user
      @user = User.find(params[:id])
      if !current_user?(@user)
        flash[:danger] = "このページへはアクセスできません"
        redirect_to(root_url)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Make every day happy with cooking'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end


  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80, cl: "gravatar")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: cl)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Your Name All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to(image_tag("header_logo.jpg", :alt => ""), root_url, id: 'logo') %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Make every day happy with cookingとは？', about_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'ユーザー一覧', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'プロフィール', current_user %></li>
              <li class="divider"></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'ユーザー登録(無料)', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="page">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "Make every day happy with cookingとは？") %>
    <h1>Make every day happy with cookingとは？</h1>

app/views/static_pages/home.html.erb
<center>
  <h1>Make every day happy with cookingへようこそ！</h1>
  <h2>自分だけのレシピ本、作りませんか？</h2>
  <p>今日のレシピ、もう迷わない！</p>
</center>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  | <%= link_to "削除", user_path(user), method: :delete,
                                data: { confirm: "本当に削除しますか？" } %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class="gravatar_edit">
      <%= gravatar_for(@user, size: 40) %>
      <%= @user.name %>
      <a href="http://gravatar.com/emails" target="_blank">プロフィール写真を変更</a>
    </div>
    <p></p>
    <div class = 'form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
    </div>
    <div class = 'form-group'>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', id: 'user_email' %>
    </div>
    <div class = 'form-group'>
      <%= f.label :introduction %>
      <%= f.text_area :introduction, size: "60x4", class: 'form-control', id: 'user_introduction' %>
    </div>
    <div class = 'form-group'>
      <%= f.label :sex %>
      <%= f.text_field :sex, class: 'form-control', id: 'user_sex' %>
    </div>
    <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<div class="container">
  <h1>ユーザー一覧</h1>
  <%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = 'form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation' %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "プロフィール") %>
<div class="container">
  <h3 class="title-profile">プロフィール</h3>
  <div class="row">
    <div class="col-md-4">
      <div class="user-picture-box">
        <%= gravatar_for @user, size: 120, cl: "gravatar user-picture" %>
      </div>
    </div>
    <div class="col-md-8">
      <h4 class="show-user-name"><%= @user.name %></h4> <%= @user.gender %>
    <div>
        <%= @user.introduction %>
    </div>
      <% if current_user == @user %>
    <div class="account-edit"><%= link_to "プロフィール編集", edit_user_path(@user) %></div>
      <% end %>
    </div>
  </div>
</div>